config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # Route to redirect user to dashboard upon successful sign in.
  get '/user' => "pages#dashboard", :as => :user_root
  get '/dashboard' => "pages#dashboard"

  resources :notifications, only: %i[index]

  resources :grandparents do
    resources :bookings, only: %i[new create edit update index show]
    resources :reviews, only: %i[new create index]
  end
  

  resources :bookings, only: %i[destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :grandparent

  # validates :description, :location, :interest, :availability, presence: true
  # validates :grandparent_id, presence: true
  # validates :user_id, presence: true
  after_create :notify_user

  private
  def notify_user
    notification = BookingNotification.with(booking: self)
    notification.deliver(grandparent.user)
  end

  validates :date, :title, :description, presence: true
 end

app/models/grandparent.rb
class Grandparent < ApplicationRecord
  belongs_to :user

  validates :name, :description, :interest, :location, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  has_many :grandparent
  validates :name,:description,:rating,  presence: true
  #review model
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :timeoutable, :validatable

  has_many :grandparents
  has_many :notifications, as: :recipient

  def unchecked_notifications
    notifications.where("created_at > ?", last_checked_notifications)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :index
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def after_sign_in_path_for(resource)
    # if current_user.grandparents.count.zero?
    #   stored_location_for(resource)
    # else
      user_root_path
    # end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: %i[show edit update destroy]

  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @grandparent = Grandparent.find(params[:grandparent_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @grandparent = Grandparent.find(params[:grandparent_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.grandparent = @grandparent
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :title, :description, :comment)
  end

  def find_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/controllers/grandparents_controller.rb
class GrandparentsController < ApplicationController
  # skip_before_action :authenticate_user!, only: :index
  before_action :find_grandparent, only: %i[show edit update destroy]

  def index
    @grandparents = policy_scope(Grandparent).order(created_at: :desc)
    @markers = @grandparents.geocoded.map do |grandparent|
      {
        lat: grandparent.latitude,
        lng: grandparent.longitude,
        info_window: render_to_string(partial: "info_window", locals: { grandparent: grandparent }),
        image_url: helpers.asset_url("grandparent_cartoon.png")
      }
    end
  end

  def new
    @grandparent = Grandparent.new
    authorize @grandparent
  end

  def create
    @grandparent = Grandparent.new(grandparent_params)
    @grandparent.user = current_user
    authorize @grandparent
    if @grandparent.save!
      redirect_to grandparent_path(@grandparent)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @grandparent.update(grandparent_params)
    redirect_to grandparent_path(@grandparent)
  end

  def destroy
    @grandparent.destroy
    redirect_to grandparents_path
  end

  private

  def grandparent_params
    params.require(:grandparent).permit(
      :name,
      :description,
      :location,
      :interest,
      :image,
      :monday,
      :tuesday,
      :wednesday,
      :thursday,
      :friday,
      :saturday,
      :sunday
    )
  end

  def find_grandparent
    @grandparent = Grandparent.find(params[:id])
    authorize @grandparent
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  skip_after_action :verify_policy_scoped

  def index
    # def unchecked_notifications
    #   notifications.where("created_at > ?", last_checked_notifications)
    # end
    @notifications = current_user.unchecked_notifications
    render
    Thread.new do
      current_user.update(last_checked_notifications: DateTime.now)
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @grandparents = policy_scope(Grandparent)
    @bookings = policy_scope(Booking)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to review_path
    else
      render :new
    end
  end

  def index
    @reviews = Review.all
  end

  private

  def review_params
    params.require(:review).permit(:rating, :booking_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
 <div class="container d-flex justify-content-center align-items-center">
  <div class="row">
    <div class="col-sm" style="margin: 32px; background-color: #61eb34">
      <h1>Confirmed</h1>
      <% @bookings.each do |booking| %>
      <div class="card-trip m-3 d-flex flex-column justify-content-start">
        <img src=<%= booking.grandparent.image %> />
        <div class="card-trip-infos">
        <div>
          <h2><strong><%= booking.title %></strong></h2> <br>
          <p><strong>Booking Date: </strong><%= booking.date.to_s[0..-8]%></p> <br>
          <p><strong>Booking Description: </strong><%= booking.description %></p>
          <br>
          <button type="button" class="btn btn-primary">View Booking</button>
        </div>
        </div>
        <div class="container d-flex justify-content-between align-items-center mb-3">
        <p></p>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-sm" style="margin: 32px; background-color: #eb4634">
      <h1>Unconfirmed</h1>
      <% @bookings.each do |booking| %>
      <div class="card-trip m-3 d-flex flex-column justify-content-start">
        <img src=<%= booking.grandparent.image %> />
        <div class="card-trip-infos">
        <div>
          <h2><strong><%= booking.title %></strong></h2> <br>
          <p><strong>Booking Date: </strong><%= booking.date.to_s[0..-8]%></p> <br>
          <p><strong>Booking Description: </strong><%= booking.description %></p>
          <br>
          <button type="button" class="btn btn-success">Confirm Booking</button>
        </div>
        </div>
        <div class="container d-flex justify-content-between align-items-center mb-3">
        <p></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 shadow p-5 mb-5 bg-body rounded mt-3">
      <h1 class="mx-auto my-3" style="text-align: center;">New Booking with <%= @grandparent.name %></h1>
      <img src="<%= @grandparent.image %>" alt="" class="my-3 w-100">
        <h2 style="text-align: center;">Availability</h2>
        <div class="mb-3 d-flex justify-content-center">
          <div class="mx-2">
            <h4 class="m-0" style="text-align: center;">M</h4>
            <%= @grandparent.monday ? '✅' : '❌' %>
          </div>
          <div class="mx-2" style="text-align: center;">
            <h4 class="m-0">T</h4>
            <%= @grandparent.tuesday ? '✅' : '❌' %>
          </div>
          <div class="mx-2" style="text-align: center;">
            <h4 class="m-0">W</h4>
            <%= @grandparent.wednesday ? '✅' : '❌' %>
          </div>
          <div class="mx-2" style="text-align: center;">
            <h4 class="m-0">T</h4>
            <%= @grandparent.thursday ? '✅' : '❌' %>
          </div>
          <div class="mx-2" style="text-align: center;">
            <h4 class="m-0">F</h4>
            <%= @grandparent.friday ? '✅' : '❌' %>
          </div>
          <div class="mx-2" style="text-align: center;">
            <h4 class="m-0">S</h4>
            <%= @grandparent.saturday ? '✅' : '❌' %>
          </div>
          <div class="mx-2">
            <h4 class="m-0" style="text-align: center;">S</h4>
            <%= @grandparent.sunday ? '✅' : '❌' %>
          </div>
        </div>
      <%= simple_form_for [@grandparent, @booking] do |f| %>
        <%= f.input :date %>
        <%= f.input :title, label: "Booking Title" %>
        <%= f.input :description %>
        <%= f.button :submit, "Book now", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/grandparents/_info_window.html.erb
<div class="container">
  <%= image_tag grandparent.image, alt: "Grandparent", class: "rounded-circle", style: "width: 150px; height: 150px; object-fit: cover;" %>
  <h3><%= grandparent.name %></h3>
  <p><%= grandparent.location %></p>
  <%= link_to "View #{grandparent.name}'s Profile", grandparent_path(grandparent), class: "btn btn-primary" %>
</div>

app/views/grandparents/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <h1 class="mx-auto my-3" style="text-align: center;">Edit Profile</h1>
        <%= simple_form_for @grandparent do |f| %>
          <%= f.input :name %>
          <%= f.input :description, label: 'About Me' %>
          <%= f.input :interest, label: 'Interests' %>
          <%= f.input :location %>
          <%= f.input :image, label: 'Link to Profile Image' %>
          <%= f.submit "Submit Changes", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/grandparents/index.html.erb
<%= render 'shared/categorytab'%>
<div class="container">
  <div style="width: 100%; height: 600px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
<div class="container my-4 d-flex">
  <div class="row w-100">
    <div class="col-md-12 d-flex flex-column justify-content-between align-items-center">
      <div class="container-fluid d-flex justify-content-center flex-wrap w-100">
        <% @grandparents.each do |grandparent| %>
          <div class="card-trip m-3 d-flex flex-column justify-content-start rounded">
            <img src=<%= grandparent.image %>  class="rounded"/>
            <div class="card-trip-infos">
              <div>
                <h2 class="mb-2"><%= grandparent.name %></h2>
                <p style="font-size: 16px;" class="mb-2">"<%= grandparent.description %>"</p>
                <p style="font-size: 16px;">Interests: <%= grandparent.interest %></p>
              </div>
            </div>
            <div class="container d-flex justify-content-between align-items-center mb-3">
              <p style="font-size: 16px; color: black;"><i class="fa-solid fa-map-location-dot"></i> - <%= grandparent.location %></p>
              <%= link_to "Details", grandparent_path(grandparent), class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
    </div>
    </div>
  </div>
</div>

app/views/grandparents/info_window.html.erb
<img src=<%= grandparent.image %> width="200" height="100"/>
<h3><%= grandparent.name %></h3>
<p><%= grandparent.location %></p>
<button type="button" class="btn btn-primary">View <%= grandparent.name %>'s Profile</button>

app/views/grandparents/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <h1 class="mx-auto my-3" style="text-align: center;">New Grandparent Profile</h1>
        <%= simple_form_for @grandparent do |f| %>
          <%= f.input :name %>
          <%= f.input :description, label: 'About Me' %>
          <%= f.input :interest, label: 'Interests' %>
          <h4>Availability:</h4>
          <div class="d-flex flex-column">
            <%= f.input :monday %>
            <%= f.input :tuesday %>
            <%= f.input :wednesday %>
            <%= f.input :thursday %>
            <%= f.input :friday %>
            <%= f.input :saturday %>
            <%= f.input :sunday %>
          </div>
          <%= f.input :location,
          input_html: { data: { geocoder_target: "location" }, class: 'd-none' },
          wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } }
          %>
          <%= f.input :image, label: 'Link to Profile Image' %>
          <%= f.submit "Create Profile", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/grandparents/show.html.erb
<div class="container my-3 shadow decor">
  <div class="row d-flex justify-content-between">
    <div class="col-6 justify-content-start rounded-large" style="background-image: url(<%= @grandparent.image%>); background-size: auto; background-repeat: no-repeat; background-position: center;">
    </div>

    <div class="col-6 grandparent_details">
        <h1 style="text-align: center;" class="w-100" id="name-title"><%= @grandparent.name %>'s Profile</h1>
          <h2>About Me</h2>
          <p><%= @grandparent.description %></p>
          <h2>Interests</h2>
          <p><%= @grandparent.interest %></p>
          <h2>Location</h2>
          <p><%= @grandparent.location.capitalize %></p>

        <div class="availability-placement border border-primary d-flex justify-content-end">
            <h2 style="title-head mb-3 d-flex justify-content-end">Availability</h2>
            <div class="mb-3 d-flex justify-content-top">
          <div class="mx-2">
            <h4 class="m-0">M</h4>
            <%= @grandparent.monday ? '✅' : '❌' %>
          </div>
          <div class="mx-2">
            <h4 class="m-0">T</h4>
            <%= @grandparent.tuesday ? '✅' : '❌' %>
          </div>
          <div class="mx-2">
            <h4 class="m-0">W</h4>
            <%= @grandparent.wednesday ? '✅' : '❌' %>
          </div>
          <div class="mx-2">
            <h4 class="m-0">T</h4>
            <%= @grandparent.thursday ? '✅' : '❌' %>
          </div>
          <div class="mx-2">
            <h4 class="m-0">F</h4>
            <%= @grandparent.friday ? '✅' : '❌' %>
          </div>
          <div class="mx-2">
            <h4 class="m-0">S</h4>
            <%= @grandparent.saturday ? '✅' : '❌' %>
          </div>
          <div class="mx-2">
            <h4 class="m-0">S</h4>
            <%= @grandparent.sunday ? '✅' : '❌' %>
          </div>
        </div>

        </div>
        <% unless policy(@grandparent).edit? %>
          <%= link_to "Book", new_grandparent_booking_path(@grandparent), class: "btn btn-outline-success mb-3 button_1" %>
          <% end %>
        <div>
          <% if policy(@grandparent).edit? %>
            <%= link_to "Edit Profile", edit_grandparent_path(@grandparent), class: "btn btn-outline-primary button_2" %>
          <% end %>
          <% if policy(@grandparent).destroy? %>
            <%= link_to "Delete Profile", grandparent_path(@grandparent), method: :delete, class: "btn-outline-danger button_3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HireAGrandparent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "Hire A Grandparent" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Grandparents are the parents of a person's father or mother – paternal or maternal. Hire someone elses today!" %>">
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload", defer: true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/75bcdb668a.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render 'shared/flashes' %>
  <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notifications/index.html.erb
<div class="container" style="height: 70vh; margin-top: 24px;">
  <% if current_user.unchecked_notifications.count == 0 %>
    <h1>No New Notifications</h1>
    <%= link_to "View Dashboard", user_root_path, class:"btn btn-outline-primary p-100" %>
    <%= link_to "Search Grandparents", grandparents_path, class:"btn btn-outline-primary p-100" %>
  <% else current_user.unchecked_notifications.count > 0  %>
    <% @notifications.each do |notification| %>
      <div class="card-product" style="border-radius: 15px; height: 170px;">
      <% grandparent = notification.params[:booking].grandparent %>
      <% booking = notification.params[:booking] %>
        <img src=<%= notification.params[:booking].grandparent.image %> style="object-fit: cover; width: 250px;">
        <div class="card-product-infos pt-22">
            <h2>New Booking: "<%= booking.title %>" with <%= grandparent.name %></h2>
            <p><%= booking.description %></p>
            <p><b>Booking Date:</b> <%= booking.date.to_s[0..-8] %></p>
            <%= link_to "View Booking", user_root_path, class:"btn btn-outline-primary p-100 d-flex justify-content flex-end" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1 class="mt-3">Your Dashboard</h1>
  <div class="container mt-4 d-flex">
    <div class="row w-100">
      <h1>My Bookings</h1>
      <div class="col-md-12 d-flex flex-column justify-content-between align-items-center">
        <div class="container d-flex flex-wrap justify-content-between align-items-center">
          <% @bookings.each do |booking| %>
            <div class="card-trip m-3 d-flex flex-column justify-content-start">
              <img src=<%= booking.grandparent.image %> />
              <div class="card-trip-infos">
                <div>
                  <h2><strong><%= booking.title %></strong></h2> <br>
                  <p><strong>Booking Date: </strong><%= booking.date.to_s[0..-8]%></p> <br>
                  <p><strong>Booking Description: </strong><%= booking.description %></p>
                </div>
              </div>
              <div class="container d-flex justify-content-between align-items-center mb-3">
                <p></p>
              </div>
            </div>
          <% end %>
      </div>
      </div>
      <div class="container mt-4 d-flex">
    <div class="row w-100">
      <h1>My Profiles</h1>
      <div class="col-md-12 d-flex flex-column justify-content-between align-items-center">
        <div class="container d-flex flex-wrap justify-content-between align-items-center">
          <% @grandparents.each do |grandparent| %>
            <% if grandparent.user == current_user %>
              <div class="card-trip m-3 d-flex flex-column justify-content-start">
                <img src=<%= grandparent.image %> />
                <div class="card-trip-infos">
                  <div>
                    <h2><%= grandparent.name %></h2>
                    <p style="font-size: 16px;">Quote: <%= grandparent.description %></p>
                    <p style="font-size: 16px;">Interests: <%= grandparent.interest %></p>
                  </div>
                </div>
                <div class="container d-flex justify-content-between align-items-center mb-3">
                  <h2><i class="fa-solid fa-map-location-dot"></i> - <%= grandparent.location %></h2>
                  <%= link_to "Details", grandparent_path(grandparent), class: "btn btn-primary" %>
                </div>
              </div>
            <% end %>
          <% end %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="row-justify-content-center">
    <div class="col-12">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "grandparent_cartoon.png" %>
      <h2 class="mx-3">Hire-a-Grandparent</h2>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav nav-pills me-auto d-flex align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.unchecked_notifications.count == 0 %>
              <li class="nav-item dropdown">
                <span class="btn btn-outline-secondary mx-1 rounded-pill">Notifications<i class="fa-regular fa-bell avatar" id="navbardropdowngp" style="font-size: 18px; color: #D9D9D9;" data-bs-toggle="dropdown" aria-haspopup="true", aria-expanded="true"></i></span>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "0 Notifications", notifications_path, class: "dropdown-item" %>
                </div>
              </li>
            <% elsif current_user.unchecked_notifications.count == 1  %>
              <li class="nav-item dropdown">
                <span class="btn btn-outline-secondary mx-1 rounded-pill">Notifications</span><i class="fa-solid fa-bell avatar" id="navbardropdowngp" style="font-size: 18px; color: #dc3545;" data-bs-toggle="dropdown" aria-haspopup="true", aria-expanded="true"></i>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "#{current_user.unchecked_notifications.count} Notification", notifications_path, class: "dropdown-item" %>
                </div>
              </li>
            <% else current_user.unchecked_notifications.count > 1  %>
              <li class="nav-item dropdown">
                <span class="btn btn-outline-secondary mx-1 rounded-pill">Notifications</span><i class="fa-solid fa-bell avatar" id="navbardropdowngp" style="font-size: 18px; color: #dc3545;" data-bs-toggle="dropdown" aria-haspopup="true", aria-expanded="true"></i>
                <%= image_tag "https://i.imgur.com/zEBX1U4.png", class: "avatar dropdown-toggle", id: "navbardropdowngp", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': true %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "#{current_user.unchecked_notifications.count} Notifications", notifications_path, class: "dropdown-item" %>
                </div>
              </li>
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to "Grandparents", grandparents_path, class: "btn btn-outline-secondary mx-1 rounded-pill" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", user_root_path, class: "btn btn-outline-secondary mx-1 rounded-pill" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': true %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <b class="dropdown-item">User: <%= current_user.first_name %></b>
              <%= link_to "Add Grandparent", new_grandparent_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item" type="button">
            <%= link_to "Become a Grandparent", new_grandparent_path, class: "btn btn-outline-secondary mx-1 rounded-pill" %>
          </li>

          <li class="nav-item" type="button">
            <%= link_to "FAQ", "#", class: "btn btn-outline-secondary mx-1 rounded-pill" %>
          </li>

          <li class="nav-item" type="button">
            <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-secondary mx-1 rounded-pill" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>